sudo: required
services:
  - docker
env:
  global:
    - REGISTRY_USER=keysoutsourcedocker
    - REGISTRY_PASS=Loveisblind2@2*
    -secret: "myrobot"
script:
  - docker build --tag keysoutsourcedocker/exampleapplication .
  - docker run keysoutsourcedocker/exampleapplication

after_script:
- docker images

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
deploy:
  provider: script
  script: docker push keysoutsourcedocker/exampleapplication
  on:
    branch: master

    